echo off

set CUR_YYYY=%date:~10,4%
set CUR_MM=%date:~4,2%
set CUR_DD=%date:~7,2%
set CUR_HH=%time:~0,2%
if %CUR_HH% lss 10 (set CUR_HH=0%time:~1,1%)

set CUR_NN=%time:~3,2%
set CUR_SS=%time:~6,2%
set CUR_MS=%time:~9,2%

if %CUR_DD% ==04 set AY=APRIL
if %CUR_DD% ==05 set AY=MAY
if %CUR_DD% ==06 set AY=JUNE
if %CUR_DD% ==07 set AY=JUL
if %CUR_DD% ==08 set AY=AGUST
if %CUR_DD% ==09 set AY=SEPTEMBER
if %CUR_DD% ==10 set AY=OCTOBER


set SUBFILENAME=%CUR_MM%.%CUR_DD%.%CUR_YYYY%
mkdir DAILY\%AY%\%SUBFILENAME%
mkdir DAILY\%AY%\%SUBFILENAME%\ERAY
mkdir DAILY\%AY%\%SUBFILENAME%\ERAY\1
mkdir DAILY\%AY%\%SUBFILENAME%\ERAY\2
mkdir DAILY\%AY%\%SUBFILENAME%\ERAY\3
mkdir DAILY\%AY%\%SUBFILENAME%\FURKAN
mkdir DAILY\%AY%\%SUBFILENAME%\FURKAN\1
mkdir DAILY\%AY%\%SUBFILENAME%\FURKAN\2
mkdir DAILY\%AY%\%SUBFILENAME%\FURKAN\3
mkdir DAILY\%AY%\%SUBFILENAME%\HUGO
mkdir DAILY\%AY%\%SUBFILENAME%\HUGO\1
mkdir DAILY\%AY%\%SUBFILENAME%\HUGO\2
mkdir DAILY\%AY%\%SUBFILENAME%\HUGO\3
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS
mkdir "DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\A LA CARTE"
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\AMPHITHEATRE
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\BAR
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\SUNSET
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\POOL
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\SLIDES
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\BEACH
mkdir "DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\WATER SPORTS"
mkdir DAILY\%AY%\%SUBFILENAME%\SIDEPHOTOS\ROAD
mkdir PRINT\%AY%\%SUBFILENAME%
